learning_log/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('learning_logs.urls')),
]

learning_logs/urls.py
"""定义 learning_logs 的URL模式"""
from django.urls import path

from . import views

app_name = 'learning_logs'
urlpatterns=[
	# 主页
	path('', views.index, name='index'),
	# 显示所有的主题
	path('topics/',views.topics, name='topics'),
	path('topics/<int:topic_id>/', views.topic, name='topic'),
	# 用于添加新主题的页面
	path('new_topic/', views.new_topic, name='new_topic'),
	path('new_entry/<int:topic_id>/', views.new_entry,name='new_entry'),
	path('edit_entry/<int:entry_id>/', views.edit_entry,name='edit_entry'),
]

users/urls.py
"""为应用程序users定义URL模式"""
from django.urls import path, include
from . import views

app_name = 'users'
urlpatterns = [
	# 包含默认的身份验证URL
	path('', include('django.contrib.auth.urls')),
	path('register/', views.register, name='register'),
]
 

learning_logs/models.py
from django.db import models
from django.contrib.auth.models import User

class Topic(models.Model):
	"""用户学习的主体"""
	text = models.CharField(max_length=200)
	date_added = models.DateTimeField(auto_now_add=True)

	owner = models.ForeignKey(User, on_delete=models.CASCADE)

	def __str__(self):
		"""返回模型的字符串表示"""
		return self.text


class Entry(models.Model):
	"""学到有关某个主题的具体知识"""
	topic = models.ForeignKey(Topic,on_delete=models.CASCADE)
	text = models.TextField()
	date_added = models.DateTimeField(auto_now_add=True)

	class Meta:
		verbose_name_plural = 'entries'

	def __str__(self):
		"""返回模型的字符串表示"""
		if len(self.text) > 50:
			return f"{self.text[:50]}..."
		else:
			return self.text

users/models.py
from django.db import models

# Create your models here.

learning_logs/forms.py
from django import forms

from .models import Topic,Entry

class TopicForm(forms.ModelForm):
	class Meta:
		model = Topic
		fields = ['text']
		labels = {'text': ''}


class EntryForm(forms.ModelForm):
	class Meta:
		model = Entry
		fields = ['text']
		labels = {'text': ''}
		widgets = {'text': forms.Textarea(attrs={'cols': 80})}

learning_logs/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.http import Http404

from .models import Topic, Entry
from .forms import TopicForm,EntryForm

def index(request):
	"""学习笔记主页"""
	return render(request,'learning_logs/index.html')

@login_required
def topics(request):
	"""显示所有的主题"""
	topics = Topic.objects.filter(owner=request.user).order_by('date_added')
	context = {'topics': topics}
	return render(request,'learning_logs/topics.html', context)

@login_required
def topic(request,topic_id):
	"""显示单个主题及其所有的条目"""
	topic = Topic.objects.get(id=topic_id)
	# 确认请求的主题属于当前用户
	if topic.owner != request.user:
		raise Http404

	entries = topic.entry_set.order_by('-date_added')
	context = {'topic':topic,'entries':entries}
	return render(request,'learning_logs/topic.html', context)


@login_required
def new_topic(request):
	"""添加新主题"""
	if request.method != 'POST':
		# 未提交数据：创建一个新表格
		form = TopicForm()
	else:
		# POST 提交的数据：对数据进行处理
		form = TopicForm(data=request.POST)
		if form.is_valid():
			new_topic = form.save(commit=False)
			new_topic.owner = request.user
			new_topic.save()
			return redirect('learning_logs:topics')


	# 显示空表单或显示表单数据无效
	context = {'form': form}
	return render(request,'learning_logs/new_topic.html',context)

@login_required
def new_entry(request,topic_id):
	"""在特定主题添加新条目"""
	topic = Topic.objects.get(id=topic_id)
	if topic.owner != request.user:
		raise Http404

	if request.method != 'POST':
		# 未提交数据：创建一个空表单
		form = EntryForm()
	else:
		# POST提交的数据：对数据进行处理
		form = EntryForm(data=request.POST)
		if form.is_valid():
			new_entry = form.save(commit=False)
			new_entry.topic = topic
			new_entry.save()
			return redirect('learning_logs:topic', topic_id=topic_id)

	# 显示空表单或指出数据无效
	context = {'topic': topic, 'form': form}
	return render(request, 'learning_logs/new_entry.html', context)

@login_required
def edit_entry(request,entry_id):
	"""编辑既有条目"""
	entry = Entry.objects.get(id=entry_id)
	topic = entry.topic

	if topic.owner != request.user:
		raise Http404

	if request.method != 'POST':
		# 初次请求： 使用当前条目填充表单
		form = EntryForm(instance=entry)
	else:
		# POST提交的数据：对象进行处理
		form = EntryForm(instance=entry, data=request.POST)
		if form.is_valid():
			form.save()
			return redirect('learning_logs:topic', topic_id=topic.id)

	context={'entry':entry,'topic':topic,'form':form}
	return render(request, 'learning_logs/edit_entry.html', context)

users/views.py
from django.shortcuts import render,redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm


def register(request):
	"""注册新用户"""
	if request.method != 'POST':
		# 线是空的注册表单
		form = UserCreationForm()
	else:
		#处理填写好的表单
		form = UserCreationForm(data = request.POST)

		if form.is_valid():
			new_user = form.save()
			# 让用户自动登录，并重新定向主页
			login(request, new_user)
			return redirect('learning_logs:index')

		# 显示空表单或指出表单无效
	context = {'form': form}
	return render(request, 'registration/register.html', context)

learning_logs/templates/learning_logs/base.html
{% load bootstrap4 %}

<!doctype html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, 	shrink-to-fit=no">
	<title>Learning Log</title>

	{% bootstrap_css %}
	{% bootstrap_javascript jquery='full' %}
</head>
<body>
	
	<nav class="navbar navbar-expand-md navbar-light bg-light mb-4 border">
		<a class="navbar-brand" href="{% url 'learning_logs:index' %}">
				Learning Log</a>

		<button class="navbar-toggler" type="button" data-toggle="collapse		"data-target="#navbarCollapse" aria-controls="navbarCollapse"
				aria-expanded="false" aria-controls="navbarCollapse">
			<span class="navbar-toggler-icon"></span></button>
		<div class="collapse navbar-collapse" id="navbarCollapse">
			<ul class="navbar-nav mr-auto">
				<li class="nav-item">
					<a class="nav-link" href="{% url 'learning_logs:topics' %}">
							Topics</a></li>
			</ul>
			<ul class="navbar-nav ml-auto" >
				{% if user.is_authenticated %}
					<li class="nav-item">
						<span class="navbar-text">Hello, {{ user.username }}.</span>
					</li>
					<li class="nav-item">
						<a class="nav-link" href="{% url 'users:logout' %}">Log out</a>
					</li>
				{% else %}
					<li class="nav-item">
						<a class="nav-link" href="{% url 'users:register' %}">Register</a>
					</li>
					<li class="nav-item">
						<a class="nav-link" href="{% url 'users:login' %}">Log in</a></li>
				{% endif %}
			</ul>
		</div>
	</nav>	
	<main role="main" class="container">
		<div class="pd-2 mb-2 border-bottom">
			{% block page_header %}{% endblock page_header %}
		</div>
		<div>
			{% block content %}{% endblock content %}
		</div>
	</main>
</body>

</html>

learning_logs/templates/learning_logs/edit_entry.html
{% extends "learning_logs/base.html" %}
{% load bootstrap4 %}

{% block page_header %}

	<h3><a href="{% url 'learning_logs:topic' topic.id %}">{{topic}}</a></h3>

{% endblock page_header %}

{% block content %}

	<p>Edit entry:</p>
		<form action="{% url 'learning_logs:edit_entry' entry.id %}" method="post">

			{% csrf_token %}
			{{form.as_p}}
			{% buttons %}
			<button name="submit" class="btn btn-primary">Save changes</button>
			{% endbuttons %}
	</form>

{% endblock content %}

learning_logs/templates/learning_logs/index.html
{% extends "learning_logs/base.html" %}

{% block page_header %}
	<div class="jumbotron">
		<h1 class="display-3">Track your learning.</h1>

		<p class="lead">Make your own Learning Log, and keep a list of the topics you're learning about. Whenever you learn something new about a topic, make an entry summarizing what you've learned.
		</p>

		<a class="btn btn-lg btn-primary" href="{% url 'users:register' %}" role="button">Register &raquo;</a>
	</div>
{% endblock page_header %}

learning_logs/templates/learning_logs/new_entry.html
{% extends "learning_logs/base.html" %}
{% load bootstrap4 %}

{% block page_header %}

<h3>
<a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a>
</h3>

{% endblock page_header %}

{% block content %}

<p>Add a new entry:</p>
	<form action="{% url 'learning_logs:new_entry' topic.id %}" method="	post">
		{% csrf_token %}
		{{ form.as_p }}
		{% buttons %}
		<button name="submit" class="btn btn-primary">Add new entry</button>
		{% endbuttons %}
	</form>

{% endblock content %}

learning_logs/templates/learning_logs/new_topic.html
{% extends "learning_logs/base.html" %}
{% load bootstrap4 %}
{% block page_header %}
	<h3>Add a new topic:</h3>
{% endblock page_header %}

{% block content %}

	<form method="post" action="{% url 'learning_logs:new_topic' %}" class="form">
		{% csrf_token %}
		{% bootstrap_form form %}
		{% buttons %}
			<button name="submit" class="btn btn-primary">Add topic</button>
		{% endbuttons %}
	</form>

{% endblock content %}

learning_logs/templates/learning_logs/topic.html
{% extends 'learning_logs/base.html' %}

{% block page_header %}
	<h3>{{ topic }}</h3>
{% endblock page_header %}

{% block content %}
	<p>
		<a href="{% url 'learning_logs:new_entry' topic.id %}">Add new entry</a>
	</p>

	{% for entry in entries %}
		<div class="card mb-3">
			<h4 class="card-header">
				{{ entry.date_added|date:'M d, Y H:i' }}
				<small><a href="{% url 'learning_logs:edit_entry' entry.id %}"		>eidt entry</a></small>
			</h4>
			<div class="card-body">
				{{ entry.text|linebreaks }}
			</div>
		</div>
	{% empty %}
		<p>There are no entries for this topic yet.</p>
	{% endfor %}
	</ul>

{% endblock content %}

learning_logs/templates/learning_logs/topics.html
{% extends "learning_logs/base.html" %}

{% block page_header %}
	<h1>Topics</h1>
{% endblock page_header %}

{% block content %}

	<ul>
		{% for topic in topics %}
			<li><h3>
			<a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a>
			</h3></li>
		{% empty %}
			<li><h3>No topics have been added yet.</h3></li>
		{% endfor %}
	</ul>

	<h3><a href="{% url 'learning_logs:new_topic' %}">Add a new topic</a></h3>

{% endblock content %}	